spring.application.name=web-shop-java

spring.threads.virtual.enabled=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
admin.password=${PASSWORD}

logging.level.org.hibernate.orm.jdbc.bind=trace
spring.jpa.properties.hibernate.generate_statistics=true